# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nuevo_producto.ui'
#
# Created: Sun Jun  8 22:09:02 2014
#      by: pyside-uic 0.2.13 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(364, 584)
        self.formLayoutWidget = QtGui.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 351, 283))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.txt_codigo = QtGui.QLineEdit(self.formLayoutWidget)
        self.txt_codigo.setObjectName("txt_codigo")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.txt_codigo)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.txt_nom_prod = QtGui.QLineEdit(self.formLayoutWidget)
        self.txt_nom_prod.setObjectName("txt_nom_prod")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.txt_nom_prod)
        self.label_3 = QtGui.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.txt_desc = QtGui.QLineEdit(self.formLayoutWidget)
        self.txt_desc.setObjectName("txt_desc")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.txt_desc)
        self.txt_atrib = QtGui.QLineEdit(self.formLayoutWidget)
        self.txt_atrib.setObjectName("txt_atrib")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.txt_atrib)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_4)
        self.txt_color = QtGui.QLineEdit(self.formLayoutWidget)
        self.txt_color.setObjectName("txt_color")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.txt_color)
        self.txt_pb = QtGui.QLineEdit(self.formLayoutWidget)
        self.txt_pb.setObjectName("txt_pb")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.txt_pb)
        self.txt_pn = QtGui.QLineEdit(self.formLayoutWidget)
        self.txt_pn.setObjectName("txt_pn")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.txt_pn)
        self.label_6 = QtGui.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_6)
        self.label_8 = QtGui.QLabel(self.formLayoutWidget)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_8)
        self.label_7 = QtGui.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_7)
        self.label_5 = QtGui.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_5)
        self.label_9 = QtGui.QLabel(self.formLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_9)
        self.cbx_marca = QtGui.QComboBox(self.formLayoutWidget)
        self.cbx_marca.setObjectName("cbx_marca")
        self.cbx_marca.addItem("")
        self.cbx_marca.addItem("")
        self.cbx_marca.addItem("")
        self.cbx_marca.addItem("")
        self.cbx_marca.addItem("")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.cbx_marca)
        self.horizontalLayoutWidget = QtGui.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 280, 311, 131))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        #self.pvw_img = KImageFilePreview(self.horizontalLayoutWidget)
        #self.pvw_img.setObjectName("pvw_img")
        #self.horizontalLayout_2.addWidget(self.pvw_img)
        self.btn_img = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.btn_img.setObjectName("btn_img")
        self.horizontalLayout_2.addWidget(self.btn_img)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(80, 460, 206, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_cancg = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.btn_cancg.setObjectName("btn_cancg")
        self.horizontalLayout.addWidget(self.btn_cancg)
        self.btn_guardar = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.btn_guardar.setObjectName("btn_guardar")
        self.horizontalLayout.addWidget(self.btn_guardar)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Datos del producto", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Código :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Nombre :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Descripción :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Color :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Atributos :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Precio Bruto :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Precio Neto :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Marca", None, QtGui.QApplication.UnicodeUTF8))
        self.cbx_marca.setItemText(0, QtGui.QApplication.translate("Dialog", "NIke", None, QtGui.QApplication.UnicodeUTF8))
        self.cbx_marca.setItemText(1, QtGui.QApplication.translate("Dialog", "Apple", None, QtGui.QApplication.UnicodeUTF8))
        self.cbx_marca.setItemText(2, QtGui.QApplication.translate("Dialog", "Samsung", None, QtGui.QApplication.UnicodeUTF8))
        self.cbx_marca.setItemText(3, QtGui.QApplication.translate("Dialog", "Reebok", None, QtGui.QApplication.UnicodeUTF8))
        self.cbx_marca.setItemText(4, QtGui.QApplication.translate("Dialog", "Microsoft", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_img.setText(QtGui.QApplication.translate("Dialog", "Seleccionar imagen", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_cancg.setText(QtGui.QApplication.translate("Dialog", "Cancelar", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_guardar.setText(QtGui.QApplication.translate("Dialog", "Guardar", None, QtGui.QApplication.UnicodeUTF8))

#from kimagefilepreview import KImageFilePreview
